name: object_detiction
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # image_picker: ^0.8.5+3

  camera: 0.10.5+9
  # flutter_tflite: ^0.6.0
  image_picker: ^0.8.4
  path_provider: ^2.0.15
  path: ^1.8.0
  flutter_tts: ^3.8.5
  flutter_tflite: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/